server:
  shutdown: graceful   # ✅ Spring Boot graceful shutdown 활성화
  servlet:
    context-path: /warehouse   # 서비스 Prefix (Ingress 경로와 동일하게)

spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s  # ✅ shutdown 단계별 타임아웃
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/warehousedb
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 5      # 최대 10개 커넥션
      #minimum-idle: 2            # 최소 2개 유휴
      #idle-timeout: 30000        # 30초 후 유휴 커넥션 제거
      #max-lifetime: 1800000      # 30분 후 커넥션 재생성
      #connection-timeout: 30000  # 30초 이상 대기 시 예외
  jpa:
    hibernate:
      # ddl-auto: 데이터베이스 스키마(테이블) 자동 생성 전략
      # create: 애플리케이션 시작 시 기존 테이블을 모두 삭제하고, 엔티티 기준으로 새로 생성
      ddl-auto: create-drop
    properties:
      hibernate:
        # 실행되는 SQL 쿼리를 보기 좋게 포맷팅하여 로그에 출력
        format_sql: true
  kafka:
    # (필수) KAFKA_BOOTSTRAP_SERVERS 환경 변수를 읽어옵니다.
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:34.84.12.79:9094}

    # -----------------------------------------------------
    # 1. 프로듀서(Producer) 설정: DTO 객체 -> JSON
    # -----------------------------------------------------
    producer:
      # 메시지 Key는 String을 사용
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 메시지 Value(내용)는 JSON으로 변환 (JsonSerializer 사용)
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"

    # -----------------------------------------------------
    # 2. 컨슈머(Consumer) 설정: JSON -> DTO 객체
    # -----------------------------------------------------
    consumer:
      # 메시지 Key는 String을 사용
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 메시지 Value(내용)는 JSON에서 DTO로 복원 (JsonDeserializer 사용)
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      # (★ 매우 중요 ★) JsonDeserializer 설정
      properties:
        spring.json.use.type.headers: false

management:
  endpoint:
    health:
      probes:
        enabled: true

  endpoints:
    web:
      exposure:
        include: health,info
